<<<<<<< HEAD
import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get('window');
=======
import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width, height } = Dimensions.get('window');
>>>>>>> the-moredern-features

export const homeStyles = StyleSheet.create({
  container: {
    flex: 1,
<<<<<<< HEAD
    backgroundColor: "#FFFFFF",
    paddingBottom: 80, // Add padding to account for tab bar
  },
  headerBackground: {
    height: 214,
    width: "100%",
  },
  headerOverlay: {
    height: "100%",
    width: "100%",
    paddingHorizontal: 16,
    paddingTop: 60,
  },
  headerContent: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  greeting: {
    fontSize: 20,
    lineHeight: 23,
    color: "#FFFFFF",
    fontWeight: "400",
  },
  welcomeBack: {
    fontSize: 20,
    lineHeight: 23,
    color: "#FFFFFF",
    fontWeight: "400",
    marginTop: 4,
  },
  headerIcons: {
    flexDirection: "row",
  },
  iconButton: {
    marginLeft: 15,
    position: 'relative',
  },
  notificationDot: {
    position: 'absolute',
    top: -2,
    right: -2,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#FF6A00',
  },
  locationContainer: {
    marginTop: 30,
  },
  locationLabel: {
    fontSize: 14,
    lineHeight: 16,
    color: "#FFFFFF",
    fontWeight: "500",
  },
  locationRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 6,
  },
  locationText: {
    fontSize: 18,
    lineHeight: 21,
    color: "#FFFFFF",
    fontWeight: "500",
    marginRight: 4,
  },
  finderCardsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    marginTop: 20,
  },
  finderCard: {
    width: (width - 40) / 2,
    height: 74,
    backgroundColor: "#FFFFFF",
    borderRadius: 15,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
    borderWidth: 1,
    borderColor: "rgba(108, 108, 108, 0.15)",
  },
  finderIconContainer: {
    marginRight: 10,
  },
  finderIcon: {
    fontSize: 24,
    color: "#000000", // Updated to black
  },
  finderText: {
    fontSize: 16,
    lineHeight: 19,
    color: "#202026", // Updated to darker color
    fontWeight: "500",
  },
  featuredContainer: {
    marginTop: 20,
    paddingHorizontal: 16,
  },
  featuredGradient: {
    borderRadius: 15,
    height: 198,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(181, 181, 181, 0.19)",
    backgroundColor: "#F5F5F5",
  },
  featuredContent: {
    flexDirection: "row",
    padding: 16,
    height: "100%",
  },
  featuredLeft: {
    width: 129,
    height: 177,
    justifyContent: "space-between",
    paddingVertical: 10,
  },
  featuredTitle: {
    fontSize: 16,
    lineHeight: 19,
    color: "#202026",
    fontWeight: "500",
    marginBottom: 10,
    width: 103,
  },
  featuredDishName: {
    fontSize: 14,
    lineHeight: 21,
    color: "#6A6A6A",
    fontWeight: "600",
    width: 97,
  },
  cookNowButton: {
    backgroundColor: "#202026",
    borderRadius: 30,
    paddingVertical: 7,
    paddingHorizontal: 15,
    alignItems: "center",
    justifyContent: "center",
    width: 100,
    marginTop: 20,
  },
  cookNowText: {
    fontSize: 14,
    lineHeight: 21,
    color: "#FFFFFF",
    fontWeight: "800",
  },
  streakContainer: {
    width: 190,
    height: 177,
    marginLeft: 10,
    justifyContent: "flex-start",
  },
  streakTitle: {
    fontSize: 16,
    lineHeight: 19,
    color: "#202026",
    fontWeight: "500",
    marginBottom: 5,
  },
  streakCard: {
    width: 157,
    height: 43,
    backgroundColor: "rgba(255, 255, 255, 0.8)",
    borderRadius: 10,
    padding: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.22,
    shadowRadius: 6,
    elevation: 3,
    marginTop: 5,
    borderWidth: 1,
    borderColor: "#FCFBFB",
  },
  streakText: {
    fontSize: 12,
    lineHeight: 18,
    color: "#6A6A6A",
    fontWeight: "600",
  },
  streakProgressContainer: {
    alignItems: "flex-end",
    marginTop: 15,
  },
  streakProgressBg: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#B5B5B5",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 4,
    borderWidth: 1,
    borderColor: "#B5B5B5",
  },
  streakProgressFill: {
    width: 57.2,
    height: 57.2,
    borderRadius: 30,
    backgroundColor: "#FF6A00",
    alignItems: "center",
    justifyContent: "center",
  },
  streakCount: {
    fontSize: 18,
    lineHeight: 21,
    color: "#202026",
    fontWeight: "500",
  },
  suggestionsContainer: {
    marginTop: 20,
    paddingHorizontal: 16,
    marginBottom: 30,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 18,
    lineHeight: 21,
    color: "#202026",
    fontWeight: "500",
  },
  sortButton: {
    width: 30,
    height: 30,
    backgroundColor: "#F9F9F9",
    borderRadius: 5,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(124, 124, 124, 0.07)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  sortIcon: {
    fontSize: 18,
    color: "#202026",
  },
  recipesContainer: {
    paddingBottom: 10,
  },
  recipeCard: {
    width: 112,
    height: 132,
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    marginRight: 15,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(124, 124, 124, 0.15)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  recipeImage: {
    width: "100%",
    height: 72,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  recipeContent: {
    padding: 8,
  },
  recipeTitle: {
    fontSize: 12,
    lineHeight: 15,
    color: "#202026",
    fontWeight: "600",
    marginBottom: 5,
  },
  recipeDetails: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  recipeDetail: {
    flexDirection: "row",
    alignItems: "center",
  },
  detailText: {
    fontSize: 10,
    lineHeight: 12,
    color: "#6A6A6A",
    fontWeight: "500",
    marginLeft: 4,
  },
  heartButton: {
    position: "absolute",
    top: 6,
    right: 6,
    width: 20,
    height: 20,
    borderRadius: 4,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 0.2,
    borderColor: "#A3A3A3",
  },
  pagination: {
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 10,
  },
  paginationDot: {
    width: 6,
    height: 6,
    borderRadius: 15,
    backgroundColor: "#B5B5B5",
    marginHorizontal: 3,
  },
  activeDot: {
    backgroundColor: "rgba(32, 32, 38, 0.4)",
=======
    backgroundColor: '#F8F8F8',
  },
  scrollContent: {
    paddingBottom: 80,
  },
  headerGradient: {
    paddingTop: Platform.OS === 'ios' ? 60 : 40,
    paddingBottom: 30,
    paddingHorizontal: 20,
  },
  headerContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  greeting: {
    fontSize: 18,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  welcomeBack: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.8)',
    marginTop: 4,
  },
  headerIcons: {
    flexDirection: 'row',
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 10,
  },
  notificationDot: {
    position: 'absolute',
    top: 10,
    right: 10,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#FF3B30',
  },
  locationContainer: {
    marginTop: 10,
  },
  locationLabel: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.8)',
    marginBottom: 4,
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  locationText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#FFFFFF',
    marginRight: 4,
  },
  finderCardsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginTop: 20,
    marginBottom: 20,
  },
  finderCard: {
    width: '48%',
    backgroundColor: '#FFFFFF',
    borderRadius: 15,
    padding: 15,
    alignItems: 'center',
    ...(Platform.OS === 'web' ? { boxShadow: '0 2px 4px rgba(0, 0, 0, 0.1)' } : {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
    }),
    elevation: 2,
  },
  finderIconContainer: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#FFF0E6',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
  },
  finderIcon: {
    fontSize: 24,
  },
  finderText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#202026',
  },
  featuredStreakContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginTop: 20,
  },
  featuredDishCard: {
    width: '48%',
    height: 180,
    backgroundColor: '#FFFFFF',
    borderRadius: 15,
    overflow: 'hidden',
    ...(Platform.OS === 'web' ? { boxShadow: '0 2px 4px rgba(0, 0, 0, 0.1)' } : {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
    }),
    elevation: 2,
    padding: 15,
  },
  featuredDishContent: {
    flex: 1,
    justifyContent: 'space-between',
  },
  featuredDishLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#202026',
    marginBottom: 8,
  },
  featuredDishName: {
    fontSize: 14,
    color: '#6A6A6A',
    lineHeight: 20,
    marginBottom: 10,
  },
  cookNowButton: {
    backgroundColor: '#202026',
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 15,
    alignItems: 'center',
    alignSelf: 'flex-start',
  },
  cookNowText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
  },
  cookingStreakCard: {
    width: '48%',
    height: 180,
    backgroundColor: '#FFFFFF',
    borderRadius: 15,
    overflow: 'hidden',
    ...(Platform.OS === 'web' ? { boxShadow: '0 2px 4px rgba(0, 0, 0, 0.1)' } : {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
    }),
    elevation: 2,
    padding: 15,
  },
  cookingStreakContent: {
    flex: 1,
  },
  cookingStreakTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#202026',
    marginBottom: 4,
  },
  cookingStreakSubtitle: {
    fontSize: 12,
    color: '#6A6A6A',
    lineHeight: 16,
    marginBottom: 15,
  },
  streakInfoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  avatarImage: {
    width: 50,
    height: 50,
    borderRadius: 25,
  },
  streakProgressContainer: {
    alignItems: 'center',
  },
  streakProgressCircle: {
    width: 50,
    height: 50,
    borderRadius: 25,
    borderWidth: 3,
    borderColor: '#000000',
    justifyContent: 'center',
    alignItems: 'center',
  },
  streakProgressText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#202026',
  },
  suggestionsContainer: {
    paddingHorizontal: 20,
    marginTop: 30,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#202026',
  },
  viewAllButton: {
    paddingVertical: 4,
    paddingHorizontal: 10,
  },
  viewAllText: {
    fontSize: 14,
    color: '#000000',
  },
  recipesContainer: {
    paddingRight: 20,
  },
  recipeCard: {
    width: 200,
    backgroundColor: '#FFFFFF',
    borderRadius: 15,
    overflow: 'hidden',
    marginRight: 15,
    ...(Platform.OS === 'web' ? { boxShadow: '0 2px 4px rgba(0, 0, 0, 0.1)' } : {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
    }),
    elevation: 2,
    borderWidth: 1,
    borderColor: 'rgba(124, 124, 124, 0.1)',
  },
  recipeImage: {
    width: '100%',
    height: 120,
  },
  recipeContent: {
    padding: 12,
  },
  recipeTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#202026',
    marginBottom: 8,
  },
  recipeDetails: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  recipeDetail: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  detailText: {
    fontSize: 12,
    color: '#6A6A6A',
    marginLeft: 4,
  },
  heartButton: {
    position: 'absolute',
    top: 10,
    right: 10,
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  pagination: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 20,
  },
  paginationDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#E0E0E0',
    marginHorizontal: 4,
  },
  activeDot: {
    backgroundColor: '#000000',
    width: 20,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    fontSize: 16,
    color: '#6A6A6A',
>>>>>>> the-moredern-features
  },
});